### ISSUE TITLE
ミーテイング 12/22

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#29]
いよいよ公開が迫ってきました！

12/22 登校します！多分15:00-16:00の間で行きます！
残件のうち，何か問題が残っていたら倒しましょう．もし全て解決できたら，喜びを噛み締めて忘年会に行きましょう．

### TODO
- [x] 0指令を入れても止まるまでに1, 2秒かかる
- [x] RobotHW で実際のwheelのIFに出力
- [x] steer_drive_controller 切れ角の問題
- [x] steer_bot_hardware_gazebo でまだ切れ角を増幅している問題
- [x] `RobotHW` を継承して`SteerRobotHWSim` を作る．

## rostest
 - [x] Jenkins とlaunch test は共存できない． → Jenkins 対応版の `indigo-devel` を作成する．
   * [x] cirkit_unit03_common
   * [x] cirkit_unit03_navigation
   * [x] cirkit_unit03_robot
   * [x] cirkit_unit03_simulator
   * [x] lower_step_detector
   * [x] human_detector
   * [x] cirkit_waypoint_manager
   * [x] timed_roslaunch
   * [x] remote_monitor

### 関連issue, pull-request
- https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/25
- https://github.com/CIR-KIT-Unit03/cirkit_unit03_robot/pull/19

### TODO
- [x] Github 側
- [x] ROS Wiki 側
  - [x] http://wiki.ros.org/Robots/CIR-KIT-Unit03 にhardware 関連の情報追加
  - [x] http://wiki.ros.org/CIR-KIT にメンバー追加
  - [x] [waypoint_generator](http://wiki.ros.org/waypoint_generator) というpkgが既に存在する．
    * [x]  `cirkit_waypoint_manager`, `cirkit_waypoint_generator`, `cirkit_waypoint_navigater` に変更する． 
  - [x] [CIR-KITのページ](http://wiki.ros.org/CIR-KIT)につくばチャレンジの集合写真を載せてよいか聞く．
- [x] Qiita記事
  - [x] ドラフトをメンバーで共有する．
  - [x] Advent Calendar 投稿．

### 関連issue, pull-request
- https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/25
- https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/26

**Comment by MoriKen254** [comment]
TODOリストを更新しました．
